# -*- coding: utf-8 -*-
#
# Pade documentation build configuration file, created by
# sphinx-quickstart on Sat Sep 12 19:30:28 2015.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath('..'))

# -- General configuration ------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.autodoc',
              'sphinx.ext.napoleon',
              'sphinx.ext.intersphinx']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Pade'
copyright = u'2019-2026, GREI-UFC'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '2.2.6'
# The full version, including alpha/beta/rc tags.
release = '2.2.6'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'pt_BR'
locale_dirs = ['locale']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

# The name of the Pygments (syntax highlighting) style to use.
# Removed flasky style as flask dependency was removed.
pygments_style = 'sphinx'

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.
sys.path.append(os.path.abspath('_themes'))
html_theme_path = ['_themes']
html_theme = 'kr'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_sidebars = {
    'index':    ['sidebarintro.html', 'sourcelink.html', 'searchbox.html'],
    '**':       ['sidebarlogo.html', 'localtoc.html', 'relations.html',
                 'sourcelink.html', 'searchbox.html']
}

# Output file base name for HTML help builder.
htmlhelp_basename = 'Padedoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The font size ('10pt', '11pt' or '12pt').
    'pointsize': '12pt',
    # Font Type
    'fontpkg': r'\usepackage{mathpazo}',
    # Removed flaskstyle preamble as the file is deprecated
    'preamble': '',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
  ('index', 'Pade.tex', u'Pade Documentation',
   u'Lucas Melo / Douglas Barros', 'manual'),
]

# Removed latex_additional_files since flaskstyle.sty is deleted.
latex_additional_files = ['logo.pdf']


# -- Options for manual page output ---------------------------------------

man_pages = [
    ('index', 'pade', u'Pade Documentation',
     [u'Lucas Melo'], 1)
]

# -- Options for Texinfo output -------------------------------------------

texinfo_documents = [
  ('index', 'Pade', u'Pade Documentation',
   u'Lucas Melo', 'Pade', 'Python Agent DEvelopment framework.',
   'Miscellaneous'),
]