#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Basic agent communication test for PADE 2026.

This test verifies:
- Creation of two agents (initiator and participant)
- A single delayed INFORM message from the initiator
- A single reply from the participant in react()
- Native logging generated by the core runtime
"""

from sys import argv

from pade.misc.utility import display_message, start_loop
from pade.core.agent import Agent
from pade.acl.messages import ACLMessage
from pade.acl.aid import AID
from pade.misc.data_logger import get_shared_session_id, logger


IGNORED_SYSTEM_MESSAGES = {
    'Agent successfully identified.',
    'CONNECTION',
}


class TestAgent(Agent):
    """Test agent that can act as initiator or participant."""

    def __init__(self, aid, participant_name=None):
        super().__init__(aid=aid, debug=False)
        self.participant_name = participant_name

    def on_start(self):
        """Called when the agent begins its activities."""
        super().on_start()
        display_message(self.aid.name, "Hello World")

        logger.log_event(
            event_type="agent_started",
            agent_id=self.aid.name,
            data={"role": "initiator" if self.participant_name else "participant"}
        )

        if self.participant_name is not None:
            display_message(self.aid.name, "⏱️ Waiting 3s to ensure AMS synchronization...")
            self.call_later(3.0, self.send_hello)

    def send_hello(self):
        """Initiator sends a single greeting to the participant."""
        message = ACLMessage(ACLMessage.INFORM)
        message.add_receiver(AID(name=self.participant_name))
        message.set_content('Hello Agent!')
        self.send(message)
        display_message(self.aid.name, 'Sending Message...')

    def react(self, message):
        """Process only application messages and reply once when required."""
        super().react(message)

        content = message.content
        if isinstance(content, bytes):
            return

        if content in IGNORED_SYSTEM_MESSAGES:
            return

        if isinstance(content, str) and content.startswith('[Agent Table:'):
            return

        display_message(self.aid.name, 'One message received')

        if self.participant_name is None and content == 'Hello Agent!':
            reply = message.create_reply()
            reply.set_content('Hello to you too, Agent!')
            self.send(reply)


if __name__ == '__main__':
    ams_config = {'name': 'localhost', 'port': 8000}
    session_id = get_shared_session_id()
    logger.log_session(
        session_id=session_id,
        name="TestAgent_Session",
        state="Started"
    )

    base_port = int(argv[1]) if len(argv) > 1 else 24000
    initiator_name = f'test_agent_initiator@localhost:{base_port}'
    participant_name = f'test_agent_participant@localhost:{base_port + 1}'

    agent_initiator = TestAgent(AID(name=initiator_name), participant_name=participant_name)
    agent_participant = TestAgent(AID(name=participant_name))

    agents = [agent_participant, agent_initiator]

    for agent in agents:
        agent.update_ams(ams_config)

    logger.log_event(
        event_type="test_started",
        data={"example": "test_agent", "num_agents": len(agents), "session_id": session_id}
    )

    display_message('System', f"🚀 Starting test with {len(agents)} agents...")
    display_message('System', "📋 Initiator will send a single message after a 3s delay")
    display_message('System', "📋 Participant will reply once after receiving it")

    start_loop(agents)
